"""empty message

Revision ID: 0f23ce52e7cd
Revises: None
Create Date: 2017-01-15 16:35:25.543613

"""

# revision identifiers, used by Alembic.
revision = '0f23ce52e7cd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('user_id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'address')
    ### end Alembic commands ###
