"""empty message

Revision ID: 8eba94c1838c
Revises: 59b25a9d6e7b
Create Date: 2017-02-24 00:38:20.074565

"""

# revision identifiers, used by Alembic.
revision = '8eba94c1838c'
down_revision = '59b25a9d6e7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('session_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('session_end', sa.TIMESTAMP(), nullable=False),
    sa.Column('isValid', sa.Boolean(), nullable=False),
    sa.Column('user_plan', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session')
    ### end Alembic commands ###
